# Generated by Django 3.1.7 on 2021-03-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0003_uset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uset',
            new_name='User',
        ),
    ]
