# Generated by Django 3.1.7 on 2021-02-28 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_add_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['salary']},
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together={('first_name', 'last_name')},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
